### ISSUE TITLE
automatically read env vars

### ISSUE THREAD

**Issue by enaut** [shantanugoel/sup#2]
https://github.com/shantanugoel/sup/blob/73826b9f5073803c10eda6ef806f4011bafa0f1d/src/cli.rs#L45-L48

I think the usual way is:
  1. read the commandline options,
  2. if option is missing read the env var.
  3. if still missing display error about missing value mentioning that it can also be provided via env var. Name the var in the error so that it is easy to setup.

That way you have less parameters.

**Comment by shantanugoel** [comment]
Fixed in 2fc49c75be5c1c4b81b99ab507008f4e773f426e
