### ISSUE TITLE
cli::Telegram and telegram::Telegram are similar

### ISSUE THREAD

**Issue by enaut** [shantanugoel/sup#3]
I don't know but to me it seems one of those could be omitted and thereby reduce the duplicated code - at least I'd rename one of the structs to make the code more readable.

for the cli option names I'd consider removing the prefixes to shorten the command that has to be entered...

But Hey I really like your little crate!

**Comment by shantanugoel** [comment]
Thanks a lot for the review :)

**Comment by enaut** [comment]
No problem - Al things I mentioned are suggestions and I'm not an expert too...

**Comment by shantanugoel** [comment]
Fixed in 9c6acc6c32a20e6540c44a1e38be10650c30c699
